name: ai-agents
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - jupyter
  - ipykernel
  - numpy
  - pandas
  - requests
  - python-dotenv
  - pip:
    # Essential AI packages
    - openai
    - semantic-kernel
    - pyautogen
    - autogen-agentchat
    
    # Azure packages
    - azure-ai-inference
    - azure-identity
    
    # Web frameworks for demos
    - chainlit
    - streamlit
    - gradio
    
    # Development essentials
    - jupyter
    - ipywidgets
